version: '3.8'

networks:
  payever:
    external: true

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: "mongodb://mongo:27017/dummy_db"
      MAILER_HOST: "sandbox.smtp.mailtrap.io"
      MAILER_PORT: 2525
    volumes:
      - app:/usr/src/app
    networks:
      - payever
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
    networks:
      - payever

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - payever

volumes:
  db-data:
  app:
